### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [galla192/my_crazy_cat_app3#2]
It looks like I'm not able to sign in to test this. Did you forget to add my user to Heroku's database?

**Comment by galla192** [comment]
How would I do that? I used heroku run rake db:migrate to move my db over to heroku, is there a different step?

**Comment by chrisvfritz** [comment]
So `rake db:migrate` actually just sets up the database with the appropriate tables and columns - it doesn't actually move any data over. Just like you set up a user in the `rails console` for your local database, you can do the same to for Heroku's database in _their_ console, accessible with `heroku run rails console`. Let me know if that helps!

**Comment by galla192** [comment]
ok its set up. should work now at the same url

**Comment by chrisvfritz** [comment]
OK, I can sign in now, but it looks like the last criterion isn't complete yet:

> NOT display any links to unauthorized actions to anonymous visitors (such as links to create a new record, edit a record, or delete a record)

**Comment by galla192** [comment]
ok ill take care of that

**Comment by galla192** [comment]
it should be fixed, let me know about any more problems

**Comment by chrisvfritz** [comment]
I still see a [link to the `edit` page here](https://crazy-cat-app.herokuapp.com/recyclers/1) when not signed in.

**Comment by galla192** [comment]
ok this is resolved too

**Comment by chrisvfritz** [comment]
:+1: Much better!
